version: '2.1'
# This is application’s services configuration for development purposes only.

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./.contrib/docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - mysql_db:/var/lib/mysql

  gulp:
    build:
      context: .
      dockerfile: .contrib/docker/Dockerfile.gulp
    ports:
      - "35729:35729"
    volumes:
      - .:/app

  web:
    # image: docker-registry.siecobywatelska.pl/poradnia/web
    build:
      context: .
      dockerfile: .contrib/docker/Dockerfile.web
      # args:
      #   PYTHON_VERSION: '${PYTHON_VERSION:-3.7}'

    volumes:
      - .:/code
    environment:
      DATABASE_URL: "mysql://root:password@db/poradnia"
      DJANGO_EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
      DJANGO_EMAIL_HOST: "maildump"
      DJANGO_EMAIL_PORT: "1025"
      DJANGO_EMAIL_USE_TLS: "False"
      DJANGO_EMAIL_HOST_PASSWORD: ""
      DJANGO_EMAIL_HOST_USER: "porady@dev.porady.siecobywatelska.pl"
      DJANGO_EMAIL_SUBJECT_PREFIX: "[poradnia_dev] "
      DJANGO_DEFAULT_FROM_EMAIL: "poradnia_dev <noreply@dev.porady.siecobywatelska.pl>"
      LETTER_RECEIVE_SECRET: "dev_letter_receive_very_secret"
      LETTER_RECEIVE_WHITELISTED_ADDRESS: ""
      DJANGO_ADMINS: "piotr.iwanski@siecobywatelska.pl,"
    ports:
      - "8000:8000"

  maildump:
    build:
      dockerfile: .contrib/docker/Dockerfile.maildump

    volumes:
      - maildump_data:/data
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  mysql_db:
  maildump_data:
