name: Python package

on: 
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  django:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: 
#           - 3.6
          - "3.10"
        django:
#           - "==2.2.*"
          - "==3.2.*"
    steps:
    - uses: actions/checkout@v1
    # Pull the latest image to build, and avoid caching pull-only images.
    # (docker pull is faster than caching in most cases.)
    - run: |
        docker-compose --file docker-compose.yml --file docker-compose.test.yml pull
        docker pull python:${{matrix.python}}-slim
    # In this step, this action saves a list of existing images,
    # the cache is created without them in the post run.
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
      with:
        key: python-${{ matrix.python }}-${{ matrix.django }}-{hash}
        restore-keys: |
          python-${{ matrix.python }}-${{ matrix.django }}-
    - name: Start database early
      run: docker-compose up -d db
    - name: Build application
      run: make build
      env:
        PYTHON_VERSION: ${{ matrix.python }}
    - name: Migration check
      run: make check
    - name: Show settings
      run: make settings
    - name: Run unit tests
      run: make test
    - name: Run e2e tests
      run: make e2e

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: docker-compose pull
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Build application
      run: make build
    - name: Build documentation
      run: make docs
