name: Docker Build and Push

on:
  pull_request:
    types:
      - closed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version from script
        id: get_version
        working-directory: poradnia
        run: |
          echo "::set-output name=version::$(python version.py)"

      - name: Get deployment env
        id: get_deployment
        run: |
          echo "::set-output name=deployment::$(if [ $GITHUB_REF == 'refs/heads/master' ]; then echo 'prod'; else echo 'staging'; fi)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .contrib/docker/Dockerfile.web
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ vars.REPO_NAME }}:latest-${{ steps.get_deployment.outputs.deployment }}
            ${{ secrets.DOCKER_USERNAME }}/${{ vars.REPO_NAME }}:${{ steps.get_version.outputs.version }}-${{ steps.get_deployment.outputs.deployment }}
